[package]
name = "dark-light"
version = "0.1.1"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/frewsxcv/rust-dark-light"
description = "Detect if dark mode or light mode is enabled"
readme = "README.md"
build = "build.rs"

[dependencies]

[target.'cfg(windows)'.dependencies]
winreg = "0.8.0"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"
