[package]
name = "dark-light"
version = "0.1.1"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/frewsxcv/rust-dark-light"
description = "Detect if dark mode or light mode is enabled"
readme = "README.md"

[dependencies]
anyhow = "1.0.52"

[target.'cfg(unix)'.dependencies]
detect-desktop-environment = "0.2.0"
dconf_rs = "0.3.0"
dirs = "4.0.0"
dbus = "0.9.5"

[target.'cfg(windows)'.dependencies]
winreg = "0.8.0"